# app/schemas/execution.py
from datetime import datetime, timezone
from typing import Any, Optional, List

from pydantic import BaseModel, Field
from app.schemas.tool_call import ToolCall


class ExecutionResult(BaseModel):
    tool_call_id: Optional[str] = Field(default=None)
    tool_id: Optional[str] = Field(default=None)
    status: str = Field(...)
    output: Optional[Any] = Field(default=None)
    error: Optional[str] = Field(default=None)
    tool_calls: List[ToolCall] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    finished_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # ==================================================
    # Added for planner_executor integration
    # ==================================================
    plan_reason: Optional[str] = Field(
        default=None,
        description="Reason for the plan generated by PlannerAgent"
    )

    # ==================================================
    # Convenience properties
    # ==================================================
    @property
    def success(self) -> bool:
        status_value = getattr(self, "status", None)
        if status_value is None:
            return False
        return str(status_value).lower() == "success"